import { SliderPageInfo } from "./types";

export const SLIDER_PAGES: SliderPageInfo[] = [
  {
    href: "/gallery/balloon-slider",
    title: "Balloon Slider",
    description: "Pump the balloon to increase volume",
    icon: "",
    color: "",
  },
  {
    href: "/gallery/bird-slider",
    title: "Bird Slider",
    description: "Play flappy bird to increase volume",
    icon: "",
    color: "",
  },
  {
    href: "/gallery/captcha-slider",
    title: "Captcha Slider",
    description: "Solve captchas to increase volume",
    icon: "",
    color: "",
  },
  {
    href: "/gallery/catapult-slider",
    title: "Catapult Slider",
    description: "Slingshot the Volume, where it lands determines your volume",
    icon: "",
    color: "",
  },
  {
    href: "/gallery/counterweight-slider",
    title: "Counterweight Slider",
    description: "scale that determines your volume",
    icon: "",
    color: "",
  },
  {
    href: "/gallery/curling-slider",
    title: "Curling Slider",
    description: "Play curling where the stone lands determines your volume",
    icon: "",
    color: "",
  },
  {
    href: "/gallery/cursed-slider",
    title: "Cursed Slider",
    description: "Counterintuitive slider",
    icon: "",
    color: "",
  },
  {
    href: "/gallery/dice-slider",
    title: "Dice Slider",
    description: "Roll the dice to determine your volume",
    icon: "",
    color: "",
  },
  {
    href: "/gallery/dino-slider",
    title: "Dino Slider",
    description: "Play the dino game to increase volume",
    icon: "",
    color: "",
  },
  {
    href: "/gallery/dropdown-slider",
    title: "Dropdown Slider",
    description: "Choose your volume from a dropdown",
    icon: "",
    color: "",
  },
  {
    href: "/gallery/hundred-sliders",
    title: "Hundred Sliders",
    description: "Use 100 sliders to control your volume",
    icon: "",
    color: "",
  },
  {
    href: "/gallery/maze-slider",
    title: "Maze Slider",
    description: "Solve mazes to increase volume",
    icon: "",
    color: "",
  },
  {
    href: "/gallery/paint-slider",
    title: "Paint Slider",
    description: "The more you cover, the higher your volume",
    icon: "",
    color: "",
  },
  {
    href: "/gallery/PI-slider",
    title: "PI Slider",
    description: "Increase your volume by writing digits of PI",
    icon: "",
    color: "",
  },
  {
    href: "/gallery/plinko-slider",
    title: "Plinko Slider",
    description: "Play plinko to get your volume",
    icon: "",
    color: "",
  },
  {
    href: "/gallery/skillcheck-slider",
    title: "Skill Check Slider",
    description: "Hit the zone to increase your volume",
    icon: "",
    color: "",
  },
  {
    href: "/gallery/snake-slider",
    title: "Snake Slider",
    description: "Play snake to increase your volume",
    icon: "",
    color: "",
  },
  {
    href: "/gallery/stacking-slider",
    title: "Stacking Slider",
    description: "Stack blocks to increase your volume",
    icon: "",
    color: "",
  },
  {
    href: "/gallery/standart-slider",
    title: "Standart Slider",
    description: "Intuitive, user-friendly slider",
    icon: "",
    color: "",
  },
  {
    href: "/gallery/tictactoe-slider",
    title: "Tic Tac Toe Slider",
    description: "Play tic tac toe to increase your volume",
    icon: "",
    color: "",
  },
  {
    href: "/gallery/tinder-slider",
    title: "Tinder Slider",
    description: "Find and match your volume",
    icon: "",
    color: "",
  },
  {
    href: "/gallery/trading-slider",
    title: "Trading Slider",
    description: "Trade your volume",
    icon: "",
    color: "",
  },
  {
    href: "/gallery/typing-slider",
    title: "Typing Slider",
    description: "Type correct to increase your volume",
    icon: "",
    color: "",
  },
  {
    href: "/gallery/wheel-slider",
    title: "Wheel Slider",
    description: "Spin the wheel to increase your volume",
    icon: "",
    color: "",
  },
];

